version: "3.8"

services:
  devise-converter:
    image: ghcr.io/linuxserver/webtop:ubuntu-xfce
    container_name: devise_converter_desktop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - .:/app
    ports:
      - 5000:3000
    restart: unless-stopped
    # On installe les dépendances au démarrage du container pour que l'app soit prête
    entrypoint: |
      /bin/bash -c "
      echo 'Installing dependencies...' &&
      pip3 install -r /app/requirement.txt &&
      echo 'Application ready. Open terminal in Webtop and run: python3 /app/app/app.py' &&
      /init"
